GET http://localhost:5000/students

###
GET http://localhost:5000/students/5f84b7da696ee51c84c3ebc6

###
POST http://localhost:5000/students
Content-Type: application/json

{
    "name": "Aruzhan",
    "surname": "Serikbayeva",
    "email": "1234",
    "phone": "1234"
}

### 
PUT http://localhost:5000/students/5f84d4691a002c3184d9667b 
Content-Type: application/json

{
    "name": "Somebody",
    "surname": "Somebody",
    "email": "somebody@gmail.com",
    "phone": "87783120332"
}

### 
DELETE http://localhost:5000/students/5f84b7da696ee51c84c3ebc6

###
POST http://localhost:5000/student/signup
Content-Type: application/json

{
   "name": "Adil",
   "surname": "Akhmetov",
   "email": "helloworld@gmail.com",
   "phone": "87783120333",
   "password": "iloveanime"
}

###
POST http://localhost:5000/student/login
Content-Type: application/json

{
   "email": "helloworld@gmail.com",
   "password": "iloveanime"
}